// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Collections documents */
interface CollectionsDocumentData {
  /**
   * Title field in *Collections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collections.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
}
/**
 * Collections document from Prismic
 *
 * - **API ID**: `collections`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CollectionsDocumentData>,
    "collections",
    Lang
  >;
/** Content for Modules documents */
interface ModulesDocumentData {
  /**
   * Title field in *Modules*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: modules.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Slice Zone field in *Modules*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: modules.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ModulesDocumentDataSlicesSlice>;
}
/**
 * Slice for *Modules → Slice Zone*
 *
 */
type ModulesDocumentDataSlicesSlice =
  | OneColumnRichtextSlice
  | FullscreenMediaSlice
  | CollectionSlice;
/**
 * Modules document from Prismic
 *
 * - **API ID**: `modules`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModulesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ModulesDocumentData>,
    "modules",
    Lang
  >;
/** Content for Pages documents */
interface PagesDocumentData {
  /**
   * Title field in *Pages*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Slice Zone field in *Pages*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PagesDocumentDataSlicesSlice>;
  /**
   * Metadata Title field in *Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.metadata_title
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  metadata_title: prismic.KeyTextField;
  /**
   * Metadata Description field in *Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.metadata_description
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  metadata_description: prismic.KeyTextField;
  /**
   * Metadata Image field in *Pages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.metadata_image
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  metadata_image: prismic.ImageField<"social">;
}
/**
 * Slice for *Pages → Slice Zone*
 *
 */
type PagesDocumentDataSlicesSlice = ModuleGroupSlice;
/**
 * Pages document from Prismic
 *
 * - **API ID**: `pages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PagesDocumentData>, "pages", Lang>;
/** Content for Product Type documents */
interface ProductTypeDocumentData {
  /**
   * Title field in *Product Type*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Slice Zone field in *Product Type*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ProductTypeDocumentDataSlicesSlice>;
}
/**
 * Slice for *Product Type → Slice Zone*
 *
 */
type ProductTypeDocumentDataSlicesSlice =
  | OneColumnRichtextSlice
  | CollectionSlice
  | FullscreenMediaSlice;
/**
 * Product Type document from Prismic
 *
 * - **API ID**: `product_type`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductTypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductTypeDocumentData>,
    "product_type",
    Lang
  >;
/** Content for Products documents */
interface ProductsDocumentData {
  /**
   * Title field in *Products*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: products.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Product Template (optional) field in *Products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: products.product_template
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  product_template: prismic.ContentRelationshipField<"product_type">;
}
/**
 * Products document from Prismic
 *
 * - **API ID**: `products`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductsDocumentData>,
    "products",
    Lang
  >;
/** Content for Site documents */
interface SiteDocumentData {
  /**
   * Title field in *Site*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: site.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Landing Page field in *Site*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: site.landing_page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  landing_page: prismic.ContentRelationshipField<"pages">;
  /**
   * Default Product Template field in *Site*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: site.default_product_template
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  default_product_template: prismic.ContentRelationshipField<"product_type">;
  /**
   * Copyright field in *Site*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site.copyright
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  copyright: prismic.RichTextField;
  /**
   * Footer Note field in *Site*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site.footer_note
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  footer_note: prismic.RichTextField;
  /**
   * Footer Navigation field in *Site*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: site.footer_navigation[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  footer_navigation: prismic.GroupField<
    Simplify<SiteDocumentDataFooterNavigationItem>
  >;
}
/**
 * Item in Site → Footer Navigation
 *
 */
export interface SiteDocumentDataFooterNavigationItem {
  /**
   * Link field in *Site → Footer Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site.footer_navigation[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
  /**
   * Link Text field in *Site → Footer Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site.footer_navigation[].link_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  link_text: prismic.RichTextField;
}
/**
 * Site document from Prismic
 *
 * - **API ID**: `site`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SiteDocumentData>, "site", Lang>;
export type AllDocumentTypes =
  | CollectionsDocument
  | ModulesDocument
  | PagesDocument
  | ProductTypeDocument
  | ProductsDocument
  | SiteDocument;
/**
 * Primary content in Collection → Primary
 *
 */
interface CollectionSliceDefaultPrimary {
  /**
   * Collection Link field in *Collection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter Collection URL
   * - **API ID Path**: collection.primary.collection_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  collection_link: prismic.LinkField;
  /**
   * Collection Handle field in *Collection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: OR enter Collection Handle
   * - **API ID Path**: collection.primary.collection_handle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  collection_handle: prismic.KeyTextField;
  /**
   * Limit Products field in *Collection → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: collection.primary.limit_products
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  limit_products: prismic.BooleanField;
  /**
   * Hide Count field in *Collection → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: collection.primary.hide_count
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hide_count: prismic.BooleanField;
  /**
   * Visible Products field in *Collection → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 4
   * - **API ID Path**: collection.primary.visible_products
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  visible_products: prismic.NumberField;
}
/**
 * Default variation for Collection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CollectionSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Collection*
 *
 */
type CollectionSliceVariation = CollectionSliceDefault;
/**
 * Collection Shared Slice
 *
 * - **API ID**: `collection`
 * - **Description**: `Collection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionSlice = prismic.SharedSlice<
  "collection",
  CollectionSliceVariation
>;
/**
 * Primary content in FullscreenMedia → Primary
 *
 */
interface FullscreenMediaSliceDefaultPrimary {
  /**
   * Image field in *FullscreenMedia → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_media.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"mobile">;
  /**
   * Video field in *FullscreenMedia → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Select Video File
   * - **API ID Path**: fullscreen_media.primary.video
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  video: prismic.LinkToMediaField;
  /**
   * External Video field in *FullscreenMedia → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_media.primary.external_video
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  external_video: prismic.LinkField;
}
/**
 * Default variation for FullscreenMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FullscreenMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullscreenMediaSliceDefaultPrimary>,
  never
>;
/**
 * Primary content in FullscreenMedia → Primary
 *
 */
interface FullscreenMediaSliceFullscreenMediaPaddedPrimary {
  /**
   * Image field in *FullscreenMedia → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_media.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"mobile">;
  /**
   * Video field in *FullscreenMedia → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Select Video File
   * - **API ID Path**: fullscreen_media.primary.video
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  video: prismic.LinkToMediaField;
  /**
   * External Video field in *FullscreenMedia → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: fullscreen_media.primary.external_video
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  external_video: prismic.LinkField;
}
/**
 * Fullscreen Media - Padded variation for FullscreenMedia Slice
 *
 * - **API ID**: `fullscreenMediaPadded`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FullscreenMediaSliceFullscreenMediaPadded =
  prismic.SharedSliceVariation<
    "fullscreenMediaPadded",
    Simplify<FullscreenMediaSliceFullscreenMediaPaddedPrimary>,
    never
  >;
/**
 * Slice variation for *FullscreenMedia*
 *
 */
type FullscreenMediaSliceVariation =
  | FullscreenMediaSliceDefault
  | FullscreenMediaSliceFullscreenMediaPadded;
/**
 * FullscreenMedia Shared Slice
 *
 * - **API ID**: `fullscreen_media`
 * - **Description**: `FullscreenMedia`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FullscreenMediaSlice = prismic.SharedSlice<
  "fullscreen_media",
  FullscreenMediaSliceVariation
>;
/**
 * Primary content in ModuleGroup → Primary
 *
 */
interface ModuleGroupSliceDefaultPrimary {
  /**
   * Group field in *ModuleGroup → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: module_group.primary.group
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  group: prismic.ContentRelationshipField<"modules">;
}
/**
 * Default variation for ModuleGroup Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ModuleGroupSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ModuleGroupSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ModuleGroup*
 *
 */
type ModuleGroupSliceVariation = ModuleGroupSliceDefault;
/**
 * ModuleGroup Shared Slice
 *
 * - **API ID**: `module_group`
 * - **Description**: `ModuleGroup`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ModuleGroupSlice = prismic.SharedSlice<
  "module_group",
  ModuleGroupSliceVariation
>;
/**
 * Primary content in OneColumnRichtext → Primary
 *
 */
interface OneColumnRichtextSliceDefaultPrimary {
  /**
   * Eyebrow field in *OneColumnRichtext → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column_richtext.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  eyebrow: prismic.RichTextField;
  /**
   * Content field in *OneColumnRichtext → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column_richtext.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField;
  /**
   * Content Alignment field in *OneColumnRichtext → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: one_column_richtext.primary.content_alignment
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  content_alignment: prismic.SelectField<"Left" | "Center", "filled">;
  /**
   * CTA Link field in *OneColumnRichtext → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column_richtext.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  cta_link: prismic.LinkField;
  /**
   * CTA Text field in *OneColumnRichtext → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column_richtext.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  cta_text: prismic.RichTextField;
}
/**
 * Default variation for OneColumnRichtext Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OneColumnRichtextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OneColumnRichtextSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *OneColumnRichtext*
 *
 */
type OneColumnRichtextSliceVariation = OneColumnRichtextSliceDefault;
/**
 * OneColumnRichtext Shared Slice
 *
 * - **API ID**: `one_column_richtext`
 * - **Description**: `OneColumnRichtext`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OneColumnRichtextSlice = prismic.SharedSlice<
  "one_column_richtext",
  OneColumnRichtextSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      CollectionsDocumentData,
      CollectionsDocument,
      ModulesDocumentData,
      ModulesDocumentDataSlicesSlice,
      ModulesDocument,
      PagesDocumentData,
      PagesDocumentDataSlicesSlice,
      PagesDocument,
      ProductTypeDocumentData,
      ProductTypeDocumentDataSlicesSlice,
      ProductTypeDocument,
      ProductsDocumentData,
      ProductsDocument,
      SiteDocumentData,
      SiteDocumentDataFooterNavigationItem,
      SiteDocument,
      AllDocumentTypes,
      CollectionSliceDefaultPrimary,
      CollectionSliceDefault,
      CollectionSliceVariation,
      CollectionSlice,
      FullscreenMediaSliceDefaultPrimary,
      FullscreenMediaSliceDefault,
      FullscreenMediaSliceFullscreenMediaPaddedPrimary,
      FullscreenMediaSliceFullscreenMediaPadded,
      FullscreenMediaSliceVariation,
      FullscreenMediaSlice,
      ModuleGroupSliceDefaultPrimary,
      ModuleGroupSliceDefault,
      ModuleGroupSliceVariation,
      ModuleGroupSlice,
      OneColumnRichtextSliceDefaultPrimary,
      OneColumnRichtextSliceDefault,
      OneColumnRichtextSliceVariation,
      OneColumnRichtextSlice,
    };
  }
}
