// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  collection: dynamic(() => import("./Collection")),
  fullscreen_media: dynamic(() => import("./FullscreenMedia")),
  module_group: dynamic(() => import("./ModuleGroup")),
  one_column_richtext: dynamic(() => import("./OneColumnRichtext")),
};
